# Generated by Django 2.1.3 on 2018-12-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_agencia', models.CharField(max_length=10)),
                ('nome_agencia', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'agencia',
                'db_table': 'agencia',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome_banco', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'banco',
                'db_table': 'banco',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('numero_conta', models.CharField(max_length=10)),
                ('dv_conta', models.CharField(max_length=2)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.Agencia')),
            ],
            options={
                'verbose_name': 'cliente',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('conta_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.Cliente')),
            ],
            options={
                'verbose_name': 'lancamento',
                'verbose_name_plural': 'lancamentos',
                'db_table': 'lancamento',
            },
        ),
        migrations.CreateModel(
            name='StatusCadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'status',
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='StatusLancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lancamento', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'status_lancamento',
                'db_table': 'status_lancamento',
            },
        ),
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo_conta',
                'db_table': 'tipo_conta',
            },
        ),
        migrations.CreateModel(
            name='TipoLancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lancamento', models.CharField(max_length=100)),
                ('is_credito_or_debito', models.CharField(choices=[('1', 'Crédito'), ('2', 'Débito'), ('3', 'Despesa Fixa')], max_length=1)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.StatusCadastro')),
            ],
            options={
                'verbose_name': 'tipo_lancamento',
                'db_table': 'tipo_lancamento',
            },
        ),
        migrations.AddField(
            model_name='lancamento',
            name='status_lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.StatusLancamento'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='tipo_lancamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.TipoLancamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.StatusCadastro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.TipoConta'),
        ),
        migrations.AddField(
            model_name='banco',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.StatusCadastro'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.Banco'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_fin.StatusCadastro'),
        ),
    ]
