# Generated by Django 2.1.3 on 2018-12-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_fin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslancamento',
            name='status_lancamento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
