# Generated by Django 2.1.3 on 2018-12-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_fin', '0002_auto_20181216_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
